version: 0.2

env:
  variables:
    NODE_OPTIONS: "--max-old-space-size=6144"

phases:
  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - yarn install

  build:
    commands:
      - yarn build

artifacts:
  base-directory: build
  files:
    - "**/*"

cache:
  paths:
    - node_modules/**/*
